Feature/remove username
mupi/tecsaladeaula pull request #55
Opened 2018-03-23 17:00 UTC by vitorandrietta

2018-03-26 13:24 UTC, rlage commented on themes/tecsaladeaula/templates/core/email/email_user_signed_up_free_course.txt
> +Você se inscreveu em nosso curtxtso gratuito {{ course_name }}.
It seems to be a typing error here.

2018-03-26 13:25 UTC, rlage approved these changes

2018-03-26 13:28 UTC, rlage requested changes
Waiting for fix

2018-03-26 14:57 UTC, rlage approved these changes

2018-03-26 14:57 UTC, merged

2018-04-09 15:20 UTC, AllanNozomu commented
fix #49 #47